project:
  type: book

book:
  title: "Notes on Modern Astrophysics"
  subtitle: "An Exploration of BOB: the Big Orange Book"
  author: "Joey Carpinelli"
  date: today
  chapters:
    - index.qmd
    - celestial-sphere.qmd
    - celestial-mechanics.qmd
    - references.qmd
  output-file: notes

csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-institute-of-aeronautics-and-astronautics.csl
bibliography: references.bib

format:
  html:
    mainfont: "'Roboto', sans-serif;"
    monofont: "'Roboto Mono', monospace;"
    title-block-banner: true
    include-in-header: 
      text: <meta name="theme-color" content="rgb(204, 100, 37)"/>
    theme: 
      light: [ pulse,  "formatting/common.scss", "formatting/light.scss" ]
      dark:  [ pulse,  "formatting/common.scss", "formatting/dark.scss"  ]
    css: formatting/styles.css
  pdf:
    documentclass: scrreprt
    extract-media: fig

primary-authors: "Caroll and Ostlie"