project:
  type: book

book:
  title: "Introduction to Modern Astrophysics"
  subtitle: "Notes on BOB: the Big Orange Book"
  author: "Joey Carpinelli"
  date: today
  chapters:
    - index.qmd
    - celestial-sphere.qmd
    - celestial-mechanics.qmd
    - references.qmd

csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-institute-of-aeronautics-and-astronautics.csl
bibliography: references.bib

format:
  html:
    mainfont: "'Roboto', sans-serif;"
    monofont: "'Roboto Mono', monospace;"
    theme: 
      light: [ pulse,  "formatting/common.scss", "formatting/light.scss" ]
      dark:  [ pulse,  "formatting/common.scss", "formatting/dark.scss"  ]
  pdf:
    documentclass: scrreprt
    output-file: notes.pdf
    extract-media: fig

primary-authors: "Caroll and Ostlie"