---
title: The Celestial Sphere
abstract: |
    Chapter 1 walks through the history Copernican Revolution in astronomy --- our 
    worldview's transition from geocentric to heliocentric. The following approximate 
    calculations are presented: sidereal and synodic periods, the Equitorial Coordinate 
    System, perturbations to the Equitorial Coorrdinates caused by a Earth's precession
    and the observed object's tangential velocity in the sky, and proper time.
---

## Retrograde Motion {#sec-retrograde}

From the point of view of observers on Earth, Mars appears to change its direction of 
motion in the night sky. This effect --- retrograde motion --- was a great motivator
for the early field of astronomy. The appearance of retrograde motion is caused by the 
planets' relative positions changing. 

The synodic period $S$, and the sidereal period $P$ are related to the discussion on 
retrograde motion. Both assume **circular orbits** about the Sun, with constant velocities. 
The synodic period relates to the oscillation of the relative position between the Earth,
and the target planet. The sidereal period relates to the duration of Earth's orientation
with respect to background stars. The two periods are related by equation (1.1) in the text,
where $P_\bigoplus$ is the sidereal period of Earth: $365.256308$ days @bob.

$$
S = \begin{cases}
1/P - 1/P_\bigoplus & \text{(inferior)} \\
1/P_\bigoplus - 1/P & \text{(superior)}
\end{cases}
$$ {#eq-synodic-sidereal-periods}

## Altitude/Azimuth {#sec-alt-az}

After I was given an [Orion ST-80](https://www.google.com/search?client=safari&rls=en&q=orion+st-80&ie=UTF-8&oe=UTF-8)
telescope in 2022, my father (a phycisist in his own right) introduced me to altitude/azimuth 
coordinates. We could use these coordinates to track objects in the night sky by orienting the 
telescope's two degrees of freedom along the horizon, and vertically "up" from the horizon to
the point on the _celestial sphere_ directly overhead the observer: the **zenith**. The 
celestial sphere coincides with two points: the point being _observed_, and the __zenith__.
The altitude coordinate $h$ is the angle from the horizontal to the observed object. The azimuth
coordinate $A$ is the angle from north along the observer-zenith axis (clockwise).
This coordinate system _says nothing_ about Earth's rotation about its axis (diurnal motion), 
or Earth's motion about the Sun (annual motion). 

## Equitorial Coordinates {#sec-equitorial}

The **Equitorial Coordinate System** also uses three coordinates, which "are based on the
latitude-longitude system of Earth but does not participate in the planet's rotation" 
@bob. The angle of declination --- $\delta$ --- corresponds to latitude. The right ascension
--- $\alpha$ --- is a kind of _longitude_ angle. The angle of right ascension is measured 
from the **vernal equinox** $\Upsilon$, counter-clockwise about the _celestial polar axis_ or meridian: 
the axis from celestial south pole to celestial north pole. Neither $\delta$ nor $\alpha$ are 
affected by the Earth's annual motion. 

The third parameter brings information about Earth's annual motion into the Equitorial 
Coordinate System: the **local sidereal time**. The hour-angle $H$
of the vernal equinox is "equivalent to" local sidereal time; the hour-angle is the angle
between the object and the observer's _meridian_, "measured in the direction of the object's"
motion around the celestial sphere" @bob. Every word in that last quote is important. We 
are encoding information about the Earth's annual motion by relating the angle of the 
object about Earth's meridian from the position of the vernal equinox, and that angle's 
_direction_ is defined _by the object's motion_. Yuck!

## Precession {#sec-precession}

Earth's rotational-axis's wobble, or **precession**, causes position of the vernal equinox
$\Upsilon$ to change, and therefore causes the right ascension and declination angles to 
change. The hour-angle of the vernal equinox, $H$, is **unchanged**. An epoch, commonly
J2000, is used to set the _origin_ local sidereal time. The drift of $\delta$ and $\alpha$
due to precession can be approximated by equations (1.2) and (1.3) in the text, where $t$
is the current date specified in fractions of a year @bob.

$$
\Delta\alpha = M + N \sin\alpha \tan\alpha
$$ {#eq-precession-right-ascension}

$$
\Delta\delta = N \cos\alpha
$$ {#eq-precession-declination}

$$
\begin{align}
M &= 1.2812323^\circ T + 0.0003879^\circ T^2 + 0.0000101 T^3 \\
N &= 0.5567530^\circ T + 0.0001185^\circ T^2 + 0.0000116 T^3 \\
\end{align}
$$ {#eq-precession-parameters}

$$
T = (t - 2000) / 100
$$ {#eq-precession-time}

## Tangential Velocity {#sec-tangential-velocity}

The motion of objects in space too causes the declination and right ascension angles
to _drift_. With a star's radial distance to from the observer $r$, and
the star's **transverse velocity** defined as $v_\theta$, the star's proper motion $\mu$ 
can be found using the text's equation (1.5) @bob. 
Using spherical trigonometry, {{< meta primary-authors >}} derive equation (1.8) in the 
text, which relates the change in angular distance traveled with the corresponding change
in declination and right ascension @bob.

$$
\mu = \frac{d \theta}{d t} = \frac{v_\theta}{r}
$$ {#eq-proper-motion}

$$
(\Delta \theta)^2 = (\Delta \alpha \cos\delta)^2 + (\Delta \delta)^2
$$ {#eq-angular-change-equitorial}